In [1]:
# Extract Data

import pandas as pd
import requests

url = "https://jsonplaceholder.typicode.com/posts"
response = requests.get(url)

data = response.json()
df = pd.DataFrame(data)

df.head()

StatementMeta(, c337b468-af3b-47f5-b8c3-e5c9cd65e08d, 3, Finished, Available, Finished, False)

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...

In [2]:
# Transform Data

df = df[['userId', 'id', 'title', 'body']]
df.columns = ['user_id', 'post_id', 'title', 'content']

df['title_length'] = df['title'].apply(len)

df.head()

StatementMeta(, c337b468-af3b-47f5-b8c3-e5c9cd65e08d, 4, Finished, Available, Finished, False)

,user_id,post_id,title,content,title_length
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...,74
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...,12
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...,59
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...,20
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...,18

In [3]:
# Load Data

spark_df = spark.createDataFrame(df)

spark_df.write.mode("overwrite").saveAsTable("posts_table")

StatementMeta(, c337b468-af3b-47f5-b8c3-e5c9cd65e08d, 5, Finished, Available, Finished, False)